### ISSUE TITLE
Warning messages when compiling with maven

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-rest-api#24] opened 2024-10-02 20:35 UTC
> [!IMPORTANT]
> Read issue #2 first

![image](https://github.com/user-attachments/assets/ccb61348-75ae-4fed-aeb0-51170c688b8e)

Investigate why these messages appear.

**Comment by ayushisingla** [comment] 2024-10-02 21:23
I can check that, you can assign this me?

**Comment by nmarulo** [comment] 2024-10-02 22:09
@ayushisingla it's all yours 👍

**Comment by nmarulo** [comment] 2024-10-04 13:14
As stated in issue #2

> When you are assigned an issue, you must confirm it by commenting on the issue within 24 hours after the assignment, this is just so I can know if you have heard or not, if I do not receive a reply I will assign it to someone else.

**Comment by ayushisingla** [comment] 2024-10-04 13:36
Hi @nmarulo , yeah, I'm working on it.

**Comment by nmarulo** [comment] 2024-10-04 13:41
@ayushisingla Ok, I assign it back to you. I just need to know that you have heard that I assigned the issue to you, regardless of whether you have started or not.

**Comment by nmarulo** [comment] 2024-10-10 13:51
As stated in issue #1

> Each issue noted with hacktoberfest must be completed within a week and you can only do one per week, this is to give more participants a chance. ...

It's okay that you were not able to complete it, I appreciate your effort and interest.

**Comment by Aryant-Tripathi** [comment] 2024-10-12 17:53
Hi, @nmarulo may I allow to check on this issue ?

**Comment by smzoha** [comment] 2024-10-12 17:54
Hey @nmarulo, would you mind if I have a look at this? I think I have found the solution already. :)

**Comment by nmarulo** [comment] 2024-10-12 19:44
@Aryant-Tripathi It's all yours 👍

**Comment by Aryant-Tripathi** [comment] 2024-10-13 10:50
Hi, @nmarulo, I am not able to start the application using docker and also on the local machine, 
getting some errors like, 


at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:205) ~[spring-beans-6.1.11.jar:6.1.11]
despensa-rest-api-1   | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:954) ~[spring-context-6.1.11.jar:6.1.11]
despensa-rest-api-1   | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:625) ~[spring-context-6.1.11.jar:6.1.11]
despensa-rest-api-1   | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.3.2.jar:3.3.2]
despensa-rest-api-1   | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.3.2.jar:3.3.2]
despensa-rest-api-1   | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.3.2.jar:3.3.2]
despensa-rest-api-1   | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:335) ~[spring-boot-3.3.2.jar:3.3.2]
despensa-rest-api-1   | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363) ~[spring-boot-3.3.2.jar:3.3.2]
despensa-rest-api-1   | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352) ~[spring-boot-3.3.2.jar:3.3.2]
despensa-rest-api-1   | 	at dev.nmarulo.depensaapp.DespensaRestApiApplication.main(DespensaRestApiApplication.java:10) ~[classes/:0.0.1]
despensa-rest-api-1   | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
despensa-rest-api-1   | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
despensa-rest-api-1   | 	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:91) ~[build/:na]
despensa-rest-api-1   | 	at org.springframework.boot.loader.launch.Launcher.launch(Launcher.java:53) ~[build/:na]
despensa-rest-api-1   | 	at org.springframework.boot.loader.launch.WarLauncher.main(WarLauncher.java:57) ~[build/:na]
despensa-rest-api-1   | Caused by: jakarta.persistence.PersistenceException: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [id] in table [products]; found [int (Types#INTEGER)], but expecting [bigint (Types#BIGINT)]


Is it expected, or I have done something wrong, likely stuck on this from last night and it's afternoon now but didn't find a way to resolve this.

**Comment by nmarulo** [comment] 2024-10-13 11:12
@Aryant-Tripathi which .yaml file are you using? the `compose.yaml` or the `compose.pantry-rest-api.yaml`?

I'm going to keep trying, to see what the error is due to.

**Comment by Aryant-Tripathi** [comment] 2024-10-13 19:36
@nmarulo So, Debug the issue, it's all because of missing JSR-305 dependency. Added dependency and it fixed.

fix: add missing JSR-305 dependency to resolve annotation processing warnings

- Issue: Compilation was generating warnings related to missing class `javax.annotation.meta.When.MAYBE` during annotation processing.
- Cause: The JSR-305 library, which includes the `javax.annotation.meta.When` enum, was not included in the classpath.
- Fix: Added the JSR-305 dependency (version 3.0.2) to the project to resolve the missing class file warnings.

This ensures that annotation processing can complete without warnings and that the required JSR-305 classes are available during the build.

**Please check with the PR.**

**Closed** 2024-10-14 20:44 UTC
Labels: hacktoberfest, Difficulty: Complex

**Comment by nmarulo** [comment] 2024-10-14 20:45
I understand that the class does not exist, but I don't understand why it is needed, so it is spring's problem that has not updated its libraries since “javax.annotation” should be updated to jakarta. Anyway, I take it for good and that's it.

Thank you very much.
